image:
  file: .gitpod.Dockerfile

tasks:
  - name: Static Server
    command: hugo server --disableFastRender --baseUrl=$(gp url 1313) --appendPort=false

ports:
  - port: 1313
    name: Hugo Server
