baseurl: "https://aohorodnyk.com/"
DefaultContentLanguage: en
title: Anton Ohorodnyk
theme: "github.com/aohorodnyk/lanyon-hugo"
pygmentsUseClasses: true

menus:
  main:
    - title: Full list of posts
      name: Home
      pageref: /
      weight: 100
    - title: About the author
      name: About
      pageref: /about/
      weight: 200

params:
  author: Anton Ohorodnyk
  title: Anton Ohorodnyk
  customCSS:
    - css/site.css
  favicon:
    color: "#262626"

taxonomies:

module:
  imports:
    - path: github.com/aohorodnyk/lanyon-hugo
