# For a description of these parameters, please visit the theme wiki.
# https://github.com/pacollins/hugo-future-imperfect-slim/wiki/config.toml
baseurl                 = "https://anton.ohorodnyk.name/"
DefaultContentLanguage  = "en"
title                   = "Anton Ohorodnyk"
theme                   = "hugo-future-imperfect-slim"
paginate                = 3
disqusShortname         = ""
googleAnalytics         = ""
pluralizeListTitles     = false
disableLanguages        = true

[markup.goldmark.renderer]
  unsafe                = true

[outputs]
  home                  = ["html", "json", "rss"]

[params]
  enableCDN             = false
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = false
  highlightjsTheme      = ""
  highlightjsLang       = []
  viewMorePostsLink     = "/blog/"
  readingTime           = true
  imageStretch          = ""
  removeBlur            = false
#  socialShare           = ["twitter", "facebook", "reddit", "linkedin", "email"]
  hideEmptyStats        = false
  author                = "Anton Ohorodnyk"
  toc                   = true
  tocWords              = 400

  [params.meta]
    description         = "Anton Ohorodnyk's blog"
    author              = "Anton Ohorodnyk"
    favicon             = true
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#262626"
    iOSColor            = "#262626"

  [params.header]
    navbarTitle         = "Anton Ohorodnyk"
    dynamicTitles       = true
    searchMenu          = true
    shareMenu           = false
    languageMenu        = false

  [params.intro]
    header                = "Anton Ohorodnyk"
    paragraph             = "Software Engineer"
    rssIntro              = true
    socialIntro           = true
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false

    [params.intro.pic]
      src                 = "/img/logo.jpg"
      shape               = "circle"
      width               = ""
      alt                 = "Anton Ohorodnyk"

  [params.sidebar]
    about               = ""
    postAmount          = 3
    categories          = false
    categoriesByCount   = true

  [params.footer]
    rssFooter           = true
    socialFooter        = true

  [params.staticman]
    enabled             = false
    api                 = ""  # No Trailing Slash
    gitProvider         = ""
    username            = ""
    repo                = ""
    branch              = "main"

    [params.staticman.recaptcha]
      siteKey           = ""
      encryptedKey      = ""

[menu]

  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = "/"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1

  [[menu.main]]
    name              = "About"
    identifier        = "about"
    url               = "/about/"
    pre               = "<i class='far fa-id-card'></i>"
    weight            = 2

  [[menu.main]]
    name              = "Blog"
    identifier        = "blog"
    url               = "/blog/"
    pre               = "<i class='far fa-newspaper'></i>"
    weight            = 3

#  [[menu.main]]
#    name              = "Categories"
#    identifier        = "categories"
#    url               = "/categories/"
#    pre               = "<i class='fas fa-sitemap'></i>"
#    weight            = 5

#  [[menu.main]]
#    name              = "Contact"
#    identifier        = "contact"
#    url               = "/contact/"
#    pre               = "<i class='far fa-envelope'></i>"
#    weight            = 6

[social]
  # Coding Communities
  github                = "aohorodnyk"
  gitlab                = ""
  stackoverflow         = "" # User Number
  bitbucket             = ""
  jsfiddle              = ""
  codepen               = ""
  # Visual Art Communities
  deviantart            = ""
  flickr                = ""
  behance               = ""
  dribbble              = ""
  # Publishing Communities
  wordpress             = ""
  medium                = ""
  # Professional/Business Oriented Communities
  linkedin              = "aohorodnyk"
  linkedin_company      = ""
  foursquare            = ""
  xing                  = ""
  slideshare            = ""
  # Social Networks
  facebook              = "aohorodnyk"
  googleplus            = ""
  reddit                = ""
  quora                 = ""
  youtube               = ""
  vimeo                 = ""
  whatsapp              = "" # WhatsApp Number
    # WeChat and QQ need testing.
    wechat              = ""
    qq                  = "" # User ID Number
  instagram             = "aohorodnyk"
  tumblr                = ""
  twitter               = "aohorodnyk"
  strava                = ""
  skype                 = ""
  snapchat              = ""
  pinterest             = ""
  telegram              = "aohorodnyk"
  vine                  = ""
  googlescholar         = ""
  orcid                 = ""
  researchgate          = ""
  keybase               = ""
  mastodon              = ""
  # Email
  email                 = "anton@ohorodnyk.name"

[markup.tableOfContents]
  startLevel = 1
  endLevel = 2