baseurl: "https://aohorodnyk.com/"
DefaultContentLanguage: en
title: Anton Ohorodnyk
pygmentsUseClasses: true

menus:
  main:
    - title: Home page
      name: Home
      pageref: /
      weight: 100
    - title: About the author
      name: Blog
      pageref: '#'
      weight: 200
      identifier: blog
    # Blog page sub-menus.
    - title: About the author
      name: Posts
      pageref: /test
      parent: blog
      weight: 100
    - title: About the author
      name: Archive
      pageref: /blog
      parent: blog
      weight: 200


params:
  ShortName: Anton O
  logo: /favicon/safari-pinned-tab.svg

build:
  noJSConfigInAssets: true
  useResourceCacheWhen: fallback
  writeStats: false
