sequenceDiagram
  participant c1 as Consumer 1
  participant c2 as Consumer 2
  participant c3 as Consumer 3
  participant p1 as Partition 1
  participant p2 as Partition 2
  par All consumers UP

  Note right of c2: No available partitions

  p1->>c1: Message 1
  p2->>c3: Message 2
  end

  Note right of c1: Consumer is down
  par Consumers 2 and 3 UP
  p1->>c2: Message 3
  p2->>c3: Message 4
  end

  Note right of c2: Consumer is down
  par Consumers 3 UP
  p1->>c3: Message 5
  p2->>c3: Message 6
  end


  par All consumers UP

  Note over c1,c3: All consumers UP

  p1->>c2: Message 7
  p2->>c3: Message 8
  end
