sequenceDiagram
  alt Callstack
    main ->> func1: Call func1()
    func1 ->> func2: Call func2()
  else Error handling
    func2 ->> func2: Check error
    func2 --> main: Throw exception
    main ->> main: Cetch exception and handle error
  end
