name: GitHub pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          extended: true

      - name: Build
        run: hugo --gc --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
      - name: Purge cache
        uses: nathanvaughn/actions-cloudflare-purge@master
        if: success()
        # preferred
        with:
          cf_zone: ${{ secrets.CLOUDFLARE_ZONE_NAME }}
          cf_auth: ${{ secrets.CLOUDFLARE_TOKEN }}
